name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # daily update
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: keshav-26-2004
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_colors: github
          plugin_languages_details: percentage
